vigetlabs/blendid

- package.json
Breaking changes in later versions prevent sass syntax from working correctly. 
See: https://github.com/dlmanning/gulp-sass/issues/173
Will update when gulp-sass issues are addressed.
Fixes #76
> Lock gulp-sass version at 1.2.4

- gulp/tasks/browserify.js
Correctly stated, there is a workaround as described in the commit message of the initial workaround. Why ever, not the full description for the workaround was provided, leave persons like me in the dark.
Added the missing workaround with using the Browserify task directly.
> Update comment about watchify bug

- gulpfile.js/lib/repeatString.js
- gulpfile.js/tasks/production.js
- package.json
.ttf fonts have an embedded timestamp, which cause the contents of the file to change ever-so-slightly. This was a problem for file reving, which generates a hash based on the contents of the file. This meant that even if source files had not changed, the hash would change with every recompile.
The solution was to only hash svg font files, then append the generate hash to the ttf, eot, and woff files.
This is just a work-around until [my pull request on svg2ttf](https://github.com/fontello/svg2ttf/pull/34) gets merged, and trickles back up to gulp-iconfont.
Also tweaked the summary output to only include reved files:
> Work around Font revving issue.

- .gitignore
You're using LibSass in `gulp-sass`. Unlike Sass, LibSass doesn't create `.sass-cache` so it's no longer necessary to include it into `.gitignore`
> Remove .sass-cache folder from .gitignore

- karma.conf.js
I hit this on a few repos and thought I'd contribute it. On larger projects, I've been bumping into timeouts on TravisCI without this optional increase to the timeout.
> [add] Higher timeout to karma config

- gulpfile.js/tasks/karma.js
See: gulpjs/gulp#587 and [Issue running karma task from gulp](http://stackoverflow.com/questions/26614738/issue-running-karma-task-from-gulp) for more information on why this is needed.
> Resolves karma issue so it will stop on test failures

- gulpfile.js/config/webpack.js
It's a bit of a small thing, but I wanted to get additional thoughts on it. This PR sets webpack to use the `context` property to define the base path for entry points.
http://webpack.github.io/docs/configuration.html#context
It's arbitrary, so no worries on skipping this one.
> [update] Use context to define base path

- src/stylesheets/global.sass
Text-align doesn't have a 'middle' property.
(Vertical-align does though, if that was intended instead..)
> Fix icon/sprite css property

- gulpfile.js/config/deploy.js
On Ubuntu, the previous config actually created a folder named tmpPROJECTNAME rather than tmp/PROJECTNAME.
Using path fixed this for me, and I think would work equally across win/mac/linux.
I've only tested on linux, but path is standardized as far as I'm aware.
> Fix os tmp dir path in deploy config

- gulpfile.js/tasks/rev/rev-assets.js
- gulpfile.js/tasks/rev/rev-css.js
- package.json
[gulp-rev-napkin](https://www.npmjs.com/package/gulp-rev-napkin) removes original files after they have been run through gulp-rev as mentioned in issue #147
> gulp-rev-napkin cleans up unhashed files after rev'ing

- README.md
while checking out gulp-starter once again I spotted this little typo. By the way I was wondering how the 4.2.x support might be?
> updated node version in documentation

- gulpfile.js/tasks/rev/update-html.js
@mzlock ran into a path issue on a craft project where she'd changed the html directory paths. This corrects where the html task rev looks for files.
> [update] paths in html rev task

- gulpfile.js/lib/webpack-multi-config.js
Taking advantage of the configuration property resolve-root. http://webpack.github.io/docs/configuration.html#resolve-root
This makes file importing inside subfolders a little easier. See example:
Now use:
import Something from 'mydir/myfile';
Old way:
import Something from '../../mydir/myfile';
> Added resolve-root jsSrc

- gulpfile.js/tasks/rev/rev-css.js
- package.json
The [gulp-minify-css package has been deprecated](https://www.npmjs.com/package/gulp-minify-css) in favor of gulp-cssnano, which should offer more advanced optimizations. 
This will remove the warning when installing.
> gulp-minify-css (deprecated) replaced with gulp-cssnano

- gulpfile.js/tasks/rev/rev-css.js
cssnano runs autoprefixer by default. This overwrites our first run with correct settings.
> Fix autoprefixer running twice

- gulpfile.js/tasks/browserSync.js
Following up on #240: 
Currently, the `browserSync.js` task will throw an error if BrowserSync is set up using a [proxy host](https://www.browsersync.io/docs/options/#option-proxy), due to the `config.tasks.browserSync.server` variable not being set.
This PR fixes this issue and enables dev middleware for proxy configs.
> Enables Webpack dev middleware for BrowserSync proxy configs

- src/javascripts/README.md
Fix minor typo in the README.md.
> Minor typo - discrete vs descrete [sic].

- gulpfile.js/tasks/browserSync.js
Referencing #263: 
If BrowserSync is configured to use a proxy and the `proxy` config setting is a string (e.g. "http://gulp.dev"), middleware will currently fail silently because BrowserSync requires `proxy` to be an object (where the hostname is the `target` attribute) in order to use middleware.
As BrowserSync permits `proxy` to be a string (where `server` is always an object), I believe Gulp Starter should handle this use case – the end user may not know/care about the middleware option or that it requires the object notation.
This PR revises the browserSync.js task in order to make middleware work for proxy configs, regardless of config format.
> Fixes issue with middleware where BrowserSync proxy is a string

- gulpfile.js/tasks/images.js
I'm not sure if subfolders were deliberately excluded but here's a PR anyway
> Fix #274: Include subdirectories when processing images

- extras/craft/gulprev/GulpRevPlugin.php
- extras/craft/gulprev/twigextensions/GulpRevTwigExtension.php
Typically, Craft uses subfolders in `/public` to set up locales.  This throws off asset versioning since the `rev-manifest.json` exists in `/public` and not the locale sub-folder (like `/public/en`).
This just adds a check for the `rev-manifest/json` file one directory up to accomodate this use-case.
> Fix Gulp Rev with locales

- gulpfile.js/tasks/html.js
Fixes #251
Only reload once at the end of the stream to keep browser from reloading too early
> Fix Browsersync html task reload issue

- gulpfile.js/config.json
The previous string incorrectly used "last 3 version" (singular form).
> Fixed the config string for autoprefixer to use "last 3 versions" (plural).

- gulpfile.js/tasks/html.js
- src/html/README.md
Allows adding custom Nunjucks filters via `task-config.js`.
For example,
```js
html: {
manageEnv: function(env) {
env.addFilter('excited', function(input) {
return (input + '!')
})
}
}
```
> Expose custom nunjucks filters to config

- extras/docker/.dockerignore
- extras/docker/Dockerfile
- extras/docker/README.md
- gulpfile.js/tasks/clean.js
I've been enjoying using gulp-starter with my Rails app. The rest of my project uses Docker, and I wanted to be able to use gulp-starter under docker-compose in development, and to build my assets when I deploy my containers to production.
The only change I had to make to the stock gulp-starter was to update the clean task. I wanted to mount my src and public folders as volumes, but when you do that, the clean task inside the container can't rm the public folder. I modified the task to delete the contents of public but not the folder itself.
Thanks again for gulp-starter, it has been invaluable for me. Hope you find this useful!
> New extra: Docker

- gulpfile.js/task-config.js
- gulpfile.js/tasks/watch.js
I need to use `usePolling: true` setting with gulp-watch in order to make it work correctly. It would be useful if this can be enabled in the config file.
> Expose gulp-watch settings

- .editorconfig
To avoid diefferent code styles we should use .editorconfig file. Maybe there are a bit more options to define. Please extend the configuration by your favor.
> Add .editorconfig for uniform code style

- gulpfile.js/tasks/production.js
In some environments the temp directory of the os is not on the same device as the code. In this case you'll get an error like "linking between cross-devices is not permitted" when replaceFiles task is executed.
My solution is to define the temp directory in the path-config file if it's needed and make sure that the directory exists when trying to write to.
> Blendid fix cross link

- package.json
due to missing version "1.9.1"
If you want to install the package previously you get an error "Invalid version". Maybe they've unpublished this version.
> Update to latest package of gulp-sourcemaps

- bin/blendid-karma.js
- bin/blendid-karma.sh
- bin/blendid.js
- bin/blendid.sh
- package.json
Previously the package was invoked (by "blendid -- build" for instance) via .sh scripts in the /bin/ directory.
Due to missing support in win32 systems for shell scripts this PR solves that by switching from .sh script to .js script that internally spawns a new child process of gulp.
> Change way of invocation from ancestor package (.sh -> .js)

- gulpfile.js/task-config.js
1. Instead of specific paths for added node_modules, it’s changed to a
generic “/node_modules”. You don’t need to edit this file to add node_modules any more.
2. Added .njk extension to the watch list. Ref.
https://mozilla.github.io/nunjucks/templating.html#file-extensions
> Generic /node_modules path and support for .njk extension

- gulpfile.js/lib/webpack-multi-config.js
The `babel-preset-react-app` plugin complains when either BABEL_ENV or NODE_ENV is not set to either 'development', 'test' or 'production'. This forces using `BABEL_ENV='development' yarn run blendid` incantation when integrating React.
To fix this, at top of webpack-multi-config, added an enforcement to setup BABEL_ENV to something. It first defaults to itself so that if already set, we do not change anything. Then, default to NODE_ENV if set and finally will be set to webpack env variable if both BABEL_ENV and NODE_ENV are not set.
> The babel-preset-react-app plugin needs BABEL_ENV or NODE_ENV

- gulpfile.js/task-config.js
- gulpfile.js/tasks/deploy.js
Exposes all options from gh-pages https://github.com/shinnn/gulp-gh-pages#api
uses the object 'deploy.ghPages' defined in task-config.js
if no 'cacheDir' option is defined, the previous defined tmp directory is used
Solves Issue #381 
PS: This is my first pull request to an open source project
> Expose gh-pages options in config

- gulpfile.js/lib/__tests__/getEnabledTasks.test.js
- gulpfile.js/lib/getEnabledTasks.js
When gulp-sequence is faced with an empty array, it seems that it will skip all following tasks in the sequence. For example, facing a call like this: `gulp.sequence('clean', [], ['build', 'assets'], 'watch')`, it will only execute 'clean'. This is caused by the array being empty.
The problem is that if all assets tasks are disabled, it shortcuts the overall sequence which prevents code tasks to be executed for example.
To overcome this, when building `assetTasks` and `codeTasks` objects, we now set them to false if there is no tasks enabled.
> Fixed problems when all asset or code tasks are disabled

- README.md
- gulpfile.js/lib/webpack-multi-config.js
- gulpfile.js/task-config.js
- package.json
- src/javascripts/app.js
- yarn.lock
Upgrades Blendid to Webpack 2, and adds a new `customizeWebpackConfig` option to gain full edit access to Blendid's environment-specific `webpackConfig`. See README updates for details.
```js
// in task-config.js
customizeWebpackConfig: function (webpackConfig, env) {
if(env === 'production') {
webpackConfig.devtool = "nosources-source-map"
}
return webpackConfig
}
```
> Webpack 2 + customizeWebpackConfig option

- README.md
- gulpfile.js/index.js
- gulpfile.js/lib/task-defaults.js
- gulpfile.js/lib/webpack-multi-config.js
- gulpfile.js/tasks/clean.js
- gulpfile.js/tasks/default.js
- gulpfile.js/tasks/html.js
- gulpfile.js/tasks/production.js
- gulpfile.js/tasks/static.js
- gulpfile.js/tasks/stylesheets.js
- gulpfile.js/tasks/svgSprite.js
- package.json
New task-config options to allow custom tasks 🎉 
Resolves #352
If anyone wants to take it for as spin:
```
yarn upgrade blendid@4.0.0-rc.12
````
If you wish to define additional gulp tasks, and have them run at a certain point in the build process, you may use this configuration to do so via the following config object:
```js
additionalTasks: {
initialize(gulp, PATH_CONFIG, TASK_CONFIG) {
// Add gulp tasks here
},
development: {
prebuild: [],
postbuild: []
},
production: {
prebuild: [],
postbuild: []
}
}
```
Blendid will call `initialize`, passing in `gulp`, along with the path and task configs. Use this method to define or `require` additional gulp tasks. You can specify when and in what order your custom tasks should run in the `production` and `development` `prebuild` and `postbuild` …
> Add custom task support

- README.md
- gulpfile.js/tasks/browserSync.js
Addresses #422 -- allows for `watchOptions` to be specified within `task-config.js` and updates the readme with an example. (note that `watch.gulpWatch` isn't in the readme, which goes hand-in-hand with this change).
Since `fsnotify` file system events won't trigger in any VirtualBox shared folders, browserSync needs `watchOptions.poll: true` in order to know to re-compile when any source files are changed.
> [#422] Add support for watchOptions in browserSync

- README.md
- gulpfile.js/tasks/browserSync.js
_Submitting a new PR as I think this got lost in the Blendid 4.0 release._
Addresses #422 -- allows for watchOptions to be specified within task-config.js and updates the readme with an example. (note that watch.gulpWatch isn't in the readme, which goes hand-in-hand with this change).
Since fsnotify file system events won't trigger in any VirtualBox shared folders, browserSync needs watchOptions.poll: true in order to know to re-compile when any source files are changed.
> [#422] add watchOptions to browserSync config

- CHANGELOG.md
- README.md
- gulpfile.js/lib/task-defaults.js
- gulpfile.js/lib/webpack-multi-config.js
- gulpfile.js/lib/webpackManifest.js
- gulpfile.js/tasks/rev/rev-assets.js
- package.json
Adds the following configuration additions:
- Add `devtool`, `uglifyJsPlugin`, and `definePlugin` environment options
- [Autoset `uglifyJsPlugin.sourceMap` to `true`](https://github.com/webpack/webpack/issues/2704#issuecomment-228860162) if `production.devtool` is defined
Resolves #232
> Add production sourcemaps

- README.md
In the suggested `package.json` additions, the double quotation marks are missing from the JSON string values.
> Add in missing quotations marks

- package.json
This small package include fix for nodejs v8. Now installation can be done with node v8.
> Update require-dir to latest

- README.md
Added a short paragraph on why imagemin isn't used in the gulp starter, and some recommendations on what to use instead.
> Explain why image-min isn't used

- README.md
- gulpfile.js/tasks/browserSync.js
Currently, the `server.middleware` config option is completely set in stone and there is no possibility to extend it. However, to be able to make React Router `<BrowserRouter>` (opposed to `<HashRouter>`) to work, one need to add a `browserSync` middleware.
To overcome the problem, two mecanisms has been added to solve this. First, if the `browserSync.server.middleware` is already defined, blendid does not try to override it anymore.
If not present, default middleware (`webpack-dev-middleware`) is used. Furthermore, the default mdidlewares from `browserSync.server.middleware` are concatenated with the ones find on config `browserSync.server.extraMiddlewares` (defaults to `[]` when none defined).
Fixed problem running on Node v8 (at least in development mode via `yarn link`) by updating …
> Prevent `browserSync.server.middleware` from being ovewritten completely

- bin/blendid.js
When using a tool like Lerna with hoisting (common dependencies installed in project root `node_modules` and not sub-project `node_modules`) or upcoming Yarn workspaces support, the resolving of `blendid` gulp main task file as well as gulp itself is broken.
The current script assumes resolution in the package directory while with these kind of tool, it get installed higher in the project hierarchy.
To solve this, we switched to `require.resolve` to resolve the actual location of the required files. This uses Node.js resolution mechanism to find the right package location.
The downside is that `require.resolve` returns the actual entry file and not the base package directory (`blendid/gulpfile.js/index.js` for `require.resolve('blendid')`). The implications is that if the entry file …
> Fixed bin script module resolving

- gulpfile.js/lib/compileLogger.js
- gulpfile.js/tasks/http2-upgrade.js
- gulpfile.js/tasks/init-config.js
- gulpfile.js/tasks/init-craft.js
- gulpfile.js/tasks/init-drupal.js
- gulpfile.js/tasks/init-rails.js
- gulpfile.js/tasks/init.js
relatively references correct files and directories needed for `gulp.dest` to build to in all init tasks.
strangely, i don't know how this ever worked before.
fixes #527
> fixes init task breaking after 4.4.0 release

- gulpfile.js/tasks/html.js
- package.json
Adds support for YAML files. Use like so:
```javascript
// in path-config.js
"html": {
"src": "html",
"dest": "./"
}
```
```javascript
// in task-config.js
html: {
dataFile: "data/global.yaml"
}
```
```yaml
message: Blendid!
```
```twig
{# some template #}
{{ message }} {# output: Blendid! #}
```
> support yaml data source in html task
