vigetlabs/blendid

gulp/config.js, package.json
re: #76 
Answers this issue as well: https://github.com/dlmanning/gulp-sass/issues/173
=> Update Sass implementation with new indentedSyntax option

package.json
No longer using browserify, so you don't need babelify.
Putting this under #97
=> Removes unused package.

gulpfile.js/config/webpack.js, package.json
Looks like I deleted my old fork. Resubmission of https://github.com/greypants/gulp-starter/pull/121
=> [update] Upgrade babel

gulpfile.js/config/deploy.js, gulpfile.js/tasks/deploy.js
Great suggestion from https://github.com/shinnn/gulp-gh-pages/issues/63#issuecomment-124779634
=> Use system temp dir for ghPages temp files

README.md
Fixes an incorrect gulp task listed for SVG Sprites.
=> [fix] Readme

gulpfile.js/tasks/iconFont/index.js
=> [fix] #193 Icons font relies on fonts config

gulpfile.js/config.json, gulpfile.js/tasks/browserSync.js, gulpfile.js/tasks/clean.js, package.json
=> [add] BrowserSync config to config.json

gulpfile.js/tasks/css.js, gulpfile.js/tasks/fonts.js, gulpfile.js/tasks/html.js, gulpfile.js/tasks/images.js, gulpfile.js/tasks/svgSprite.js
Changed browserSync.reload({stream: true}) to browserSync.stream()
=> browserSync.reload({stream: true}) is deprecated

gulpfile.js/tasks/browserSync.js, package.json
Fixes a bug where gulp tasks wouldn't properly shut down
=> [update] browserSync version and implementation

README.md
"propertiesto" fixed to "properties to" - The smallest PR I've ever made.
=> Fix typo and remove trailing whitespace

gulpfile.js/tasks/iconFont/index.js
=> Fix url issue for iconFont when build on windows platform

gulpfile.js/tasks/iconFont/index.js, package.json
=> Upgrade gulp-iconfont

.travis.yml, gulpfile.js/lib/__tests__/pathToUrl.test.js, gulpfile.js/lib/pathToUrl.js, gulpfile.js/lib/webpack-multi-config.js, gulpfile.js/tasks/browserSync.js, package.json
Resolves #262 
Also changes some minor naming related to #265.
@chaelli if you get a chance, would you mind checking out that branch and seeing if all's well?
=> Fix webpack publicPath Windows issue

extras/demo/config.json
Add production rev to the demo config file to stop gulp compile issue when copied over to the root.
=> Fix broken demo config.json

gulpfile.js/task-config.js, gulpfile.js/tasks/static.js, gulpfile.js/tasks/watch.js
=> Fix paths and glob patterns in the static and watch tasks

gulpfile.js/lib/webpack-multi-config.js, src/javascripts/README.md
We had to use the ignorePlugin and the providePlugin in webpack. This draft should make users able to easily extend the webpack behavior.
=> Support for additional plugins and loaders

gulpfile.js/lib/webpack-multi-config.js, src/javascripts/README.md
it can now be modified through "config.javascripts.babelLoader" entry in task-config.
=> Modify babel loader config 

README.md
=> Small correction in readme.

extras/craft/ASSETS-README.md
Added a link to the wiki page on Craft setup.
=> Brought this over from the main branch.

README.md
src/images/README.md has been deleted with #416
=> Broken link removed

gulpfile.js/lib/repeatString.js, gulpfile.js/tasks/sizereport.js
This package doesn’t seem to have been used for more than a year.
=> Remove repeatString

README.md
Just fixing a broken link I ran into. 
Thanks for making this!
=> Just fixes the link to the additional tasks section

gulpfile.js/tasks/production.js, gulpfile.js/tasks/replace-files.js
=> reorganizes production and replace-file tasks to ensure public directory is cleaned
